### PR TITLE
975-Remove-checked-exceptions-from-@PostConstruct-methods

### LINKED ISSUE #975: Remove checked exceptions from @PostConstruct methods
classes listed as below should remove the checked exceptions from their `@PostConstruct` methods and `@PreDestroy` methods since it fails from deploying eureka-server onto Payara.
```
eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerContext.java
eureka-core/src/main/java/com/netflix/eureka/aws/AwsBinderDelegate.java
eureka-core/src/main/java/com/netflix/eureka/aws/EIPManager.java
eureka-core/src/main/java/com/netflix/eureka/aws/ElasticNetworkInterfaceBinder.java
eureka-core/src/main/java/com/netflix/eureka/aws/Route53Binder.java
```

### PR DESCRIPTION
**Pull request by mulderbaba**
fixes #975

### CODE REVIEW

File: eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerContext.java [hunk 1]
```diff
@@ -59,16 +59,20 @@ public DefaultEurekaServerContext(EurekaServerConfig serverConfig,
...
     @Override
-    public void initialize() throws Exception {
+    public void initialize() {
         logger.info("Initializing ...");
         peerEurekaNodes.start();
-        registry.init(peerEurekaNodes);
+        try {
+            registry.init(peerEurekaNodes);
+        } catch (Exception e) {
+            logger.error("Error occurred while initializing registry", e);
```
Comment (mattnelson) [inline eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerContext.java]: Wouldn't it be better to wrap and throw as a RuntimeException instead of suppressing with a log message?

Comment (spencergibb) [inline eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerContext.java]: :+1: that way there isn't a change of behavior

File: eureka-core/src/main/java/com/netflix/eureka/aws/EIPManager.java [hunk 2]
```diff
@@ -101,20 +101,28 @@ public EIPManager(EurekaServerConfig serverConfig,
...
             try {
                 unbindEIP();
                 break;
             } catch (Exception e) {
                 logger.warn("Cannot unbind the EIP from the instance");
-                Thread.sleep(1000);
+                try {
+                    Thread.sleep(1000);
+                } catch (InterruptedException e1) {
+                    throw new RuntimeException(e);
```
Comment (qiangdavidliu) [inline eureka-core/src/main/java/com/netflix/eureka/aws/EIPManager.java]: Hi, this should be `e1` here

File: eureka-core/src/main/java/com/netflix/eureka/aws/ElasticNetworkInterfaceBinder.java [hunk 3]
```diff
@@ -93,23 +93,31 @@ public void start() throws Exception {
                 }
             } catch (Throwable e) {
                 logger.error("Cannot bind to IP", e);
-                Thread.sleep(IP_BIND_SLEEP_TIME_MS);
+                try {
+                    Thread.sleep(IP_BIND_SLEEP_TIME_MS);
+                } catch (InterruptedException e1) {
+                    throw new RuntimeException(e);
```
Comment (qiangdavidliu) [inline eureka-core/src/main/java/com/netflix/eureka/aws/ElasticNetworkInterfaceBinder.java]: should be `e1` here

File: eureka-core/src/main/java/com/netflix/eureka/aws/ElasticNetworkInterfaceBinder.java [hunk 4]
```diff
@@ -93,23 +93,31 @@ public void start() throws Exception {
...
             try {
                 unbind();
                 break;
             } catch (Exception e) {
                 logger.warn("Cannot unbind the IP from the instance");
-                Thread.sleep(IP_BIND_SLEEP_TIME_MS);
+                try {
+                    Thread.sleep(IP_BIND_SLEEP_TIME_MS);
+                } catch (InterruptedException e1) {
+                    throw new RuntimeException(e);
```
Comment (qiangdavidliu) [inline eureka-core/src/main/java/com/netflix/eureka/aws/ElasticNetworkInterfaceBinder.java]: should be `e1` here

**Comment by qiangdavidliu** [comment]
Hi @mulderbaba thanks for the PR, and apologies for the late review. Some minor comments.

**Comment by qiangdavidliu** [comment]
going to merge this and address the comments in a separate PR.
